//AUTH
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAIL = 'VERIFY_EMAIL_FAIL';
export const RESEND_VERIFICATION_CODE_REQUEST = 'RESEND_VERIFICATION_CODE_REQUEST';
export const RESEND_VERIFICATION_CODE_SUCCESS = 'RESEND_VERIFICATION_CODE_SUCCESS';
export const RESEND_VERIFICATION_CODE_FAIL = 'RESEND_VERIFICATION_CODE_FAIL';

//USER
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const EDIT_USER_INFO_REQUEST = 'EDIT_USER_INFO_REQUEST';
export const EDIT_USER_INFO_SUCCESS = 'EDIT_USER_INFO_SUCCESS';
export const EDIT_USER_INFO_FAIL = 'EDIT_USER_INFO_FAIL';
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL';
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

//REPORT
export const GET_REPORTS_REQUEST = 'GET_REPORTS_REQUEST';
export const GET_REPORTS_SUCCESS = 'GET_REPORTS_SUCCESS';
export const GET_REPORTS_FAIL = 'GET_REPORTS_FAIL';
export const CREATE_REPORT_REQUEST = 'CREATE_REPORT_REQUEST';
export const CREATE_REPORT_SUCCESS = 'CREATE_REPORT_SUCCESS';
export const CREATE_REPORT_FAIL = 'CREATE_REPORT_FAIL';
export const EDIT_REPORT_REQUEST = 'EDIT_REPORT_REQUEST';
export const EDIT_REPORT_SUCCESS = 'EDIT_REPORT_SUCCESS';
export const EDIT_REPORT_FAIL = 'EDIT_REPORT_FAIL';
export const DELETE_REPORT_REQUEST = 'DELETE_REPORT_REQUEST';
export const DELETE_REPORT_SUCCESS = 'DELETE_REPORT_SUCCESS';
export const DELETE_REPORT_FAIL = 'DELETE_REPORT_FAIL';
export const CLEAR_REPORT_STATE = 'CLEAR_REPORT_STATE';
export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';


//NOTIFICATION
export const SEND_EMAIL_REQUEST = "SEND_EMAIL_REQUEST";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAIL = "SEND_EMAIL_FAIL";

export const SEND_PUSH_NOTIFICATION_REQUEST = "SEND_PUSH_NOTIFICATION_REQUEST";
export const SEND_PUSH_NOTIFICATION_SUCCESS = "SEND_PUSH_NOTIFICATION_SUCCESS";
export const SEND_PUSH_NOTIFICATION_FAIL = "SEND_PUSH_NOTIFICATION_FAIL";

//GENERAL
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';


//ALPR
export const CREATE_ALPR_REQUEST = 'CREATE_ALPR_REQUEST';
export const CREATE_ALPR_SUCCESS = 'CREATE_ALPR_SUCCESS';
export const CREATE_ALPR_FAIL = 'CREATE_ALPR_FAIL';

export const GET_ALPR_REQUEST = 'GET_ALPR_REQUEST';
export const GET_ALPR_SUCCESS = 'GET_ALPR_SUCCESS';
export const GET_ALPR_FAIL = 'GET_ALPR_FAIL';

export const RECOGNIZE_PLATE_REQUEST = 'RECOGNIZE_PLATE_REQUEST';
export const RECOGNIZE_PLATE_SUCCESS = 'RECOGNIZE_PLATE_SUCCESS';
export const RECOGNIZE_PLATE_FAIL = 'RECOGNIZE_PLATE_FAIL';

//FEEDBACK
export const CREATE_FEEDBACK_REQUEST = 'CREATE_FEEDBACK_REQUEST';
export const CREATE_FEEDBACK_SUCCESS = 'CREATE_FEEDBACK_SUCCESS';
export const CREATE_FEEDBACK_FAIL = 'CREATE_FEEDBACK_FAIL';

export const GET_FEEDBACK_REQUEST = 'GET_FEEDBACK_REQUEST';
export const GET_FEEDBACK_SUCCESS = 'GET_FEEDBACK_SUCCESS';
export const GET_FEEDBACK_FAIL = 'GET_FEEDBACK_FAIL';

export const GET_ALL_FEEDBACK_REQUEST = 'GET_ALL_FEEDBACK_REQUEST';
export const GET_ALL_FEEDBACK_SUCCESS = 'GET_ALL_FEEDBACK_SUCCESS';
export const GET_ALL_FEEDBACK_FAIL = 'GET_ALL_FEEDBACK_FAIL';

export const GET_USER_FEEDBACK_REQUEST = 'GET_USER_FEEDBACK_REQUEST';
export const GET_USER_FEEDBACK_SUCCESS = 'GET_USER_FEEDBACK_SUCCESS';
export const GET_USER_FEEDBACK_FAIL = 'GET_USER_FEEDBACK_FAIL';


export const UPDATE_FEEDBACK_REQUEST = 'UPDATE_FEEDBACK_REQUEST';
export const UPDATE_FEEDBACK_SUCCESS = 'UPDATE_FEEDBACK_SUCCESS';
export const UPDATE_FEEDBACK_FAIL = 'UPDATE_FEEDBACK_FAIL';

export const DELETE_FEEDBACK_REQUEST = 'DELETE_FEEDBACK_REQUEST';
export const DELETE_FEEDBACK_SUCCESS = 'DELETE_FEEDBACK_SUCCESS';
export const DELETE_FEEDBACK_FAIL = 'DELETE_FEEDBACK_FAIL';

//OVERALL RATINGS
export const GET_OVERALL_RATINGS_REQUEST = 'GET_OVERALL_RATINGS_REQUEST';
export const GET_OVERALL_RATINGS_SUCCESS = 'GET_OVERALL_RATINGS_SUCCESS';
export const GET_OVERALL_RATINGS_FAIL = 'GET_OVERALL_RATINGS_FAIL';