const reportData = [
    {
      reporter: "60d0fe4f5311236168a109ca",
      missingPerson: {
        firstname: "John",
        lastname: "Doe",
        dateOfBirth: new Date("1990-01-01"),
        age: 31,
        assignedSexAtBirth: "Male",
        scarsOrMarks: "Scar on left cheek",
        prostheticsOrImplants: "None",
        lastKnownClothing: "Blue jeans and white t-shirt",
        lastKnownLocation: "Central Park, NY",
        lastSeen: new Date("2021-06-15"),
        causeOfDisappearance: "Unknown",
        currentHairColor: "Brown",
        alias: "Johnny",
        genderIdentity: "Male",
        height: "5'10\"",
        weight: "170 lbs",
        raceOrNationality: "Caucasian",
        eyeColor: "Blue",
        wearsContactLenses: false,
        bloodType: "O+",
        reward: 5000,
        images: [
          {
            public_id: "image1",
            url: "http://example.com/image1.jpg",
          },
        ],
        video: {
          public_id: "video1",
          url: "http://example.com/video1.mp4",
        },
        medication: "None",
        birthDefects: "None",
        contactNumber: "123-456-7890",
        socialMediaAccount: "@johndoe",
      },
      status: "Pending",
      category: "Missing",
      createdAt: new Date(),
    },
    {
      reporter: "60d0fe4f5311236168a109cb",
      missingPerson: {
        firstname: "Jane",
        lastname: "Smith",
        dateOfBirth: new Date("1985-05-15"),
        age: 36,
        assignedSexAtBirth: "Female",
        scarsOrMarks: "Tattoo on right arm",
        prostheticsOrImplants: "None",
        lastKnownClothing: "Red dress",
        lastKnownLocation: "Times Square, NY",
        lastSeen: new Date("2021-06-10"),
        causeOfDisappearance: "Unknown",
        currentHairColor: "Blonde",
        alias: "Janie",
        genderIdentity: "Female",
        height: "5'6\"",
        weight: "130 lbs",
        raceOrNationality: "Caucasian",
        eyeColor: "Green",
        wearsContactLenses: true,
        bloodType: "A+",
        reward: 10000,
        images: [
          {
            public_id: "image2",
            url: "http://example.com/image2.jpg",
          },
        ],
        video: {
          public_id: "video2",
          url: "http://example.com/video2.mp4",
        },
        medication: "Insulin",
        birthDefects: "None",
        contactNumber: "987-654-3210",
        socialMediaAccount: "@janesmith",
      },
      status: "Confirmed",
      category: "Abducted",
      createdAt: new Date(),
    },
    {
      reporter: "60d0fe4f5311236168a109cc",
      missingPerson: {
        firstname: "Michael",
        lastname: "Johnson",
        dateOfBirth: new Date("2000-12-25"),
        age: 20,
        assignedSexAtBirth: "Male",
        scarsOrMarks: "Birthmark on neck",
        prostheticsOrImplants: "None",
        lastKnownClothing: "Black hoodie and jeans",
        lastKnownLocation: "Brooklyn, NY",
        lastSeen: new Date("2021-06-20"),
        causeOfDisappearance: "Unknown",
        currentHairColor: "Black",
        alias: "Mike",
        genderIdentity: "Male",
        height: "6'0\"",
        weight: "180 lbs",
        raceOrNationality: "African American",
        eyeColor: "Brown",
        wearsContactLenses: false,
        bloodType: "B+",
        reward: 3000,
        images: [
          {
            public_id: "image3",
            url: "http://example.com/image3.jpg",
          },
        ],
        video: {
          public_id: "video3",
          url: "http://example.com/video3.mp4",
        },
        medication: "None",
        birthDefects: "None",
        contactNumber: "555-555-5555",
        socialMediaAccount: "@michaeljohnson",
      },
      status: "Solved",
      category: "Wanted",
      createdAt: new Date(),
    },
    {
        reporter: "60d0fe4f5311236168a109ca",
        missingPerson: {
          firstname: "John",
          lastname: "Doe",
          dateOfBirth: new Date("1990-01-01"),
          age: 31,
          assignedSexAtBirth: "Male",
          scarsOrMarks: "Scar on left cheek",
          prostheticsOrImplants: "None",
          lastKnownClothing: "Blue jeans and white t-shirt",
          lastKnownLocation: "Central Park, NY",
          lastSeen: new Date("2021-06-15"),
          causeOfDisappearance: "Unknown",
          currentHairColor: "Brown",
          alias: "Johnny",
          genderIdentity: "Male",
          height: "5'10\"",
          weight: "170 lbs",
          raceOrNationality: "Caucasian",
          eyeColor: "Blue",
          wearsContactLenses: false,
          bloodType: "O+",
          reward: 5000,
          images: [
            {
              public_id: "image1",
              url: "http://example.com/image1.jpg",
            },
          ],
          video: {
            public_id: "video1",
            url: "http://example.com/video1.mp4",
          },
          medication: "None",
          birthDefects: "None",
          contactNumber: "123-456-7890",
          socialMediaAccount: "@johndoe",
        },
        status: "Pending",
        category: "Missing",
        createdAt: new Date(),
      },
      {
        reporter: "60d0fe4f5311236168a109cb",
        missingPerson: {
          firstname: "Jane",
          lastname: "Smith",
          dateOfBirth: new Date("1985-05-15"),
          age: 36,
          assignedSexAtBirth: "Female",
          scarsOrMarks: "Tattoo on right arm",
          prostheticsOrImplants: "None",
          lastKnownClothing: "Red dress",
          lastKnownLocation: "Times Square, NY",
          lastSeen: new Date("2021-06-10"),
          causeOfDisappearance: "Unknown",
          currentHairColor: "Blonde",
          alias: "Janie",
          genderIdentity: "Female",
          height: "5'6\"",
          weight: "130 lbs",
          raceOrNationality: "Caucasian",
          eyeColor: "Green",
          wearsContactLenses: true,
          bloodType: "A+",
          reward: 10000,
          images: [
            {
              public_id: "image2",
              url: "http://example.com/image2.jpg",
            },
          ],
          video: {
            public_id: "video2",
            url: "http://example.com/video2.mp4",
          },
          medication: "Insulin",
          birthDefects: "None",
          contactNumber: "987-654-3210",
          socialMediaAccount: "@janesmith",
        },
        status: "Confirmed",
        category: "Abducted",
        createdAt: new Date(),
      },
      {
        reporter: "60d0fe4f5311236168a109cc",
        missingPerson: {
          firstname: "Michael",
          lastname: "Johnson",
          dateOfBirth: new Date("2000-12-25"),
          age: 20,
          assignedSexAtBirth: "Male",
          scarsOrMarks: "Birthmark on neck",
          prostheticsOrImplants: "None",
          lastKnownClothing: "Black hoodie and jeans",
          lastKnownLocation: "Brooklyn, NY",
          lastSeen: new Date("2021-06-20"),
          causeOfDisappearance: "Unknown",
          currentHairColor: "Black",
          alias: "Mike",
          genderIdentity: "Male",
          height: "6'0\"",
          weight: "180 lbs",
          raceOrNationality: "African American",
          eyeColor: "Brown",
          wearsContactLenses: false,
          bloodType: "B+",
          reward: 3000,
          images: [
            {
              public_id: "image3",
              url: "http://example.com/image3.jpg",
            },
          ],
          video: {
            public_id: "video3",
            url: "http://example.com/video3.mp4",
          },
          medication: "None",
          birthDefects: "None",
          contactNumber: "555-555-5555",
          socialMediaAccount: "@michaeljohnson",
        },
        status: "Solved",
        category: "Wanted",
        createdAt: new Date(),
      },
      {
        reporter: "60d0fe4f5311236168a109cd",
        missingPerson: {
          firstname: "Emily",
          lastname: "Clark",
          dateOfBirth: new Date("1995-03-10"),
          age: 26,
          assignedSexAtBirth: "Female",
          scarsOrMarks: "Small scar on right eyebrow",
          prostheticsOrImplants: "None",
          lastKnownClothing: "Green jacket and black pants",
          lastKnownLocation: "Los Angeles, CA",
          lastSeen: new Date("2021-06-18"),
          causeOfDisappearance: "Unknown",
          currentHairColor: "Red",
          alias: "Em",
          genderIdentity: "Female",
          height: "5'7\"",
          weight: "140 lbs",
          raceOrNationality: "Caucasian",
          eyeColor: "Hazel",
          wearsContactLenses: false,
          bloodType: "AB-",
          reward: 7000,
          images: [
            {
              public_id: "image4",
              url: "http://example.com/image4.jpg",
            },
          ],
          video: {
            public_id: "video4",
            url: "http://example.com/video4.mp4",
          },
          medication: "None",
          birthDefects: "None",
          contactNumber: "111-222-3333",
          socialMediaAccount: "@emilyclark",
        },
        status: "Pending",
        category: "Missing",
        createdAt: new Date(),
      },
      {
        reporter: "60d0fe4f5311236168a109ce",
        missingPerson: {
          firstname: "David",
          lastname: "Brown",
          dateOfBirth: new Date("1980-07-04"),
          age: 41,
          assignedSexAtBirth: "Male",
          scarsOrMarks: "Burn mark on left arm",
          prostheticsOrImplants: "None",
          lastKnownClothing: "White shirt and khaki pants",
          lastKnownLocation: "Seattle, WA",
          lastSeen: new Date("2021-06-12"),
          causeOfDisappearance: "Unknown",
          currentHairColor: "Gray",
          alias: "Dave",
          genderIdentity: "Male",
          height: "5'9\"",
          weight: "160 lbs",
          raceOrNationality: "Caucasian",
          eyeColor: "Brown",
          wearsContactLenses: false,
          bloodType: "O-",
          reward: 4000,
          images: [
            {
              public_id: "image5",
              url: "http://example.com/image5.jpg",
            },
          ],
          video: {
            public_id: "video5",
            url: "http://example.com/video5.mp4",
          },
          medication: "None",
          birthDefects: "None",
          contactNumber: "444-555-6666",
          socialMediaAccount: "@davidbrown",
        },
        status: "Confirmed",
        category: "Lost",
        createdAt: new Date(),
      },
      {
        reporter: "60d0fe4f5311236168a109ca",
        missingPerson: {
          firstname: "John",
          lastname: "Doe",
          dateOfBirth: new Date("1990-01-01"),
          age: 31,
          assignedSexAtBirth: "Male",
          scarsOrMarks: "Scar on left cheek",
          prostheticsOrImplants: "None",
          lastKnownClothing: "Blue jeans and white t-shirt",
          lastKnownLocation: "Central Park, NY",
          lastSeen: new Date("2021-06-15"),
          causeOfDisappearance: "Unknown",
          currentHairColor: "Brown",
          alias: "Johnny",
          genderIdentity: "Male",
          height: "5'10\"",
          weight: "170 lbs",
          raceOrNationality: "Caucasian",
          eyeColor: "Blue",
          wearsContactLenses: false,
          bloodType: "O+",
          reward: 5000,
          images: [
            {
              public_id: "image1",
              url: "http://example.com/image1.jpg",
            },
          ],
          video: {
            public_id: "video1",
            url: "http://example.com/video1.mp4",
          },
          medication: "None",
          birthDefects: "None",
          contactNumber: "123-456-7890",
          socialMediaAccount: "@johndoe",
        },
        status: "Pending",
        category: "Missing",
        createdAt: new Date(),
      },
      {
        reporter: "60d0fe4f5311236168a109ca",
        missingPerson: {
          firstname: "John",
          lastname: "Doe",
          dateOfBirth: new Date("1990-01-01"),
          age: 31,
          assignedSexAtBirth: "Male",
          scarsOrMarks: "Scar on left cheek",
          prostheticsOrImplants: "None",
          lastKnownClothing: "Blue jeans and white t-shirt",
          lastKnownLocation: "Central Park, NY",
          lastSeen: new Date("2021-06-15"),
          causeOfDisappearance: "Unknown",
          currentHairColor: "Brown",
          alias: "Johnny",
          genderIdentity: "Male",
          height: "5'10\"",
          weight: "170 lbs",
          raceOrNationality: "Caucasian",
          eyeColor: "Blue",
          wearsContactLenses: false,
          bloodType: "O+",
          reward: 5000,
          images: [
            {
              public_id: "image1",
              url: "http://example.com/image1.jpg",
            },
          ],
          video: {
            public_id: "video1",
            url: "http://example.com/video1.mp4",
          },
          medication: "None",
          birthDefects: "None",
          contactNumber: "123-456-7890",
          socialMediaAccount: "@johndoe",
        },
        status: "Pending",
        category: "Missing",
        createdAt: new Date(),
      }

    ];
  
  module.exports = reportData;